describe("criar pedido ms credito - gama.qa", () => {

  beforeEach(() => {
    cy.login_webpdv_gama();
    cy.get('#menuone > :nth-child(14)').first().click();
    cy.get('a[href="/webpdv/pedidos/criar.php"]').eq(1).click();
  });


  it("tests criar pedido ms credito - gama.qa", () => {
    cy.viewport(1356, 961);
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/pedidos/criar.php");
    cy.get('button[value="Inserir"]').click();
    cy.get("#btn_escolher_cliente").click();
    // cy.get('input[id="cpf-cnpj-cliente"]').click();
    cy.get('input[id="cpf-cnpj-cliente"]').type('15719559841');
    cy.get("html").click();
    cy.location("href").should("eq", "undefined");
    cy.get("div.menu_cliente li:nth-of-type(2) > a").click();
    cy.get("#f_int_prdno").click();
    cy.get("form div:nth-of-type(1)").click();
    cy.get("#f_int_prdno").click();
    cy.get("button > span.ui-button-text").click();
    cy.location("href").should("eq", "undefined");
    cy.get("li > ul > li:nth-of-type(1) > a").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button > span.ui-button-text").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#TB_closeWindowButton").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/pedidos/editar.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("div.menu_cliente li:nth-of-type(3) > a").click();
    cy.get("#toggleCheckboxes").click();
    cy.get("label:nth-of-type(4) > input").click();
    cy.get("#submit").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#TB_closeWindowButton").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/pedidos/editar.php?f_int_ordno=508906&f_int_storeno=25");
    cy.get("div.menu_cliente li:nth-of-type(5) > a").click();
    cy.get("#f_int_id_forma_atendimento").type("44");
    cy.get("#f_int_cardno").type("38");
    cy.get("#s2id_f_int_paymno span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#f_int_numero_parcelas").type("10");
    cy.get("#submit_formPag").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#submit").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#TB_closeWindowButton").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("#conteudo > div:nth-of-type(1) strong").click();
    cy.get("li:nth-of-type(2) > a").click();
    cy.get("#verificar_f_str_ddd_telefone").click();
    cy.get("#verificar_f_str_ddd_telefone").type("73");
    cy.get("#verificar_f_str_telefone").click();
    cy.get("#verificar_f_str_telefone").type("998043309");
    cy.get("span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("#uso > table").click();
    cy.get("tr:nth-of-type(2) > td:nth-of-type(1) img").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#tratarEndereco").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.get("#submit").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("#uso caption").click();
    cy.get("tfoot a").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("#uso caption").click();
    cy.get("li:nth-of-type(2) > a").click();
    cy.get("button.ui-state-focus > span").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("#uso caption").click();
    cy.get("li:nth-of-type(2) > a").click();
    cy.get("button.ui-state-focus > span").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("[data-cy='cameraButton'] > div > div").click();
    cy.get("[data-cy='documentCameraTutorialButton']").click();
    cy.get("div.v-dialog__content--active span").click();
    cy.get("[data-cy='closePhotoModal'] > span").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("form span").click();
    cy.visit("https://stage-backoffice-next.dinheirow.com.br/proposals?page=1");
    cy.visit("https://stage-backoffice.dinheirow.com.br/proposals?page=1");
    cy.get("html > body > #__next > div.mantine-Stack-root > div.flex > div > div.w-full > div > table > tbody > [data-testid='lineProposal'] [data-testid='proposalId']").click();
    cy.get("html").click();
    cy.get("[data-testid='assume_proposal']").click();
    cy.get("div.border-warning > button").click();
    cy.get("[data-testid='approve']").click();
    cy.get("li:nth-of-type(5) h3").click();
    cy.get("[data-testid='approveProposal']").click();
    cy.get("body > div:nth-of-type(5) div:nth-of-type(2) p").click();
    cy.get("#uso > table").click();
    cy.get("li:nth-of-type(2) > a").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("a").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("div.v-input--selection-controls__ripple").click();
    cy.get("div > div > div > div.fill-height h2").click();
    cy.get("[data-cy='screenSignature']").click();
    cy.get("[data-cy='saveSignature'] > span").click();
    cy.get("[data-cy='sendSignatureButton'] > span").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("div:nth-of-type(5) caption").click();
    cy.get("span").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://gama.qa.simonettidev.com.br:8080/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=508906");
    cy.get("#uso caption").click();
    cy.get("a").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("form > div.d-flex span").click();
    cy.get("div.v-input--selection-controls__ripple").click();
    cy.get("[data-cy='toSignButton']").click();
    cy.get("[data-cy='screenSignature']").click();
    cy.get("[data-cy='saveSignature'] > span").click();
    cy.get("[data-cy='sendSignatureButton']").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
  });
});
