describe("criar pedido fidc ms credito", () => {

  beforeEach(() => {
    cy.login_webpdv();
    cy.get('#menuone > :nth-child(16)').first().click();
    cy.get('a[href="/webpdv/pedidos/criar.php"]').eq(1).click();
  });

  it("tests criar pedido fidc ms credito", () => {
    cy.viewport(1356, 961);
    cy.get('button[value="Inserir"]').click();
    cy.get("#btn_escolher_cliente").click();
    cy.wait(2000);
    cy.get('label[for="cpf-cpnj-cliente"').type("13359774736");
    cy.get("html").click();
    cy.location("href").should("eq", "undefined");
    cy.get("div.menu_cliente li:nth-of-type(2) > a").click();
    cy.get("#f_int_prdno").click();
    cy.get("#f_int_prdno").type("504656");
    cy.get("button > span.ui-button-text").click();
    cy.location("href").should("eq", "undefined");
    cy.get("li > ul > li:nth-of-type(1) > a").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button > span.ui-button-text").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#TB_overlay").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/pedidos/editar.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("div.menu_cliente li:nth-of-type(3) > a").click();
    cy.get("#toggleCheckboxes").click();
    cy.get("label:nth-of-type(4)").click();
    cy.get("#submit").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#TB_overlay").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/pedidos/editar.php?f_int_ordno=611973&f_int_storeno=25");
    cy.get("div.menu_cliente li:nth-of-type(5) > a").click();
    cy.get("#f_int_id_forma_atendimento").type("44");
    cy.get("#f_int_cardno").type("38");
    cy.get("#s2id_f_int_paymno span").click();
    cy.get("#select2-drop input").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#f_int_numero_parcelas").type("8");
    cy.get("#submit_formPag").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#submit").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#TB_overlay").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("#conteudo > div:nth-of-type(1) tr:nth-of-type(2) > td").click();
    cy.get("li > ul > li:nth-of-type(1) > a").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("#field-\\:rd\\:").click();
    cy.get("#field-\\:rd\\:").type("ES");
    cy.get("#tabs-\\:r1\\:--tabpanel-1 > div > div > div.chakra-tabs__tab-panels button").click();
    cy.get("#tabs-\\:r2\\:--tabpanel-1 button.css-1h2tf6l").click();
    cy.get("#tabs-\\:r2\\:--tabpanel-2 button.css-1h2tf6l > svg").click();
    cy.get("#tabs-\\:r2\\:--tabpanel-3 button.css-1h2tf6l").click();
    cy.get("#conteudo > div:nth-of-type(1) strong").click();
    cy.get("li:nth-of-type(2) > a").click();
    cy.get("#verificar_f_str_ddd_telefone").click();
    cy.get("#verificar_f_str_ddd_telefone").type("27");
    cy.get("#verificar_f_str_telefone").type("999573110");
    cy.get("span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("#uso caption").click();
    cy.get("tr:nth-of-type(2) > td:nth-of-type(1) img").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#tratarEndereco").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.get("#submit").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("#conteudo > div:nth-of-type(3) th:nth-of-type(4)").click();
    cy.get("tfoot a").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("#uso caption").click();
    cy.get("li:nth-of-type(2) > a").click();
    cy.get("button.ui-state-focus > span").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("body").click();
    cy.get("#uso caption").click();
    cy.get("li:nth-of-type(2) > a").click();
    cy.get("button.ui-state-focus > span").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("[data-cy='cameraButton'] > div > div").click();
    cy.get("div.container > div > div:nth-of-type(1) div.v-responsive__content").click();
    cy.get("[data-cy='documentCameraTutorial'] span").click();
    cy.get("[data-cy='takePhotoButton']").click();
    cy.get("div.v-dialog__content--active span.v-btn__content").click();
    cy.get("[data-cy='cardPhoto']").click();
    cy.get("[data-cy='cardPhoto'] > div:nth-of-type(2) > div").click();
    cy.get("[data-cy='closePhotoModal']").click();
    cy.get("div.flex-fill > div.flex-fill > div.container").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("[data-cy='cameraButton'] > div > div").click();
    cy.get("li:nth-of-type(1)").click();
    cy.get("[data-cy='documentCameraTutorial'] span").click();
    cy.get("[data-cy='takePhotoButton']").click();
    cy.get("[data-cy='closePhotoModal'] > span").click();
    cy.get("form > div.d-flex span").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("[data-cy='cameraButton'] > div > div").click();
    cy.get("[data-cy='documentCameraTutorialButton']").click();
    cy.get("div.v-dialog__content--active span").click();
    cy.get("[data-cy='closePhotoModal']").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("#uso caption").click();
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("#uso caption").click();
    cy.get("li:nth-of-type(2) > a").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("a").click();
    cy.get("#sign").click();
    cy.get("#teste").click();
    cy.get("button.btn-save").click();
    cy.get("button.btn-confirm").click();
    cy.get("span.ui-button-text").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("div:nth-of-type(5) th:nth-of-type(3)").click();
    cy.get("span").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("button").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("img").click();
    cy.get("div.ui-dialog-buttonpane").click();
    cy.get("div.ui-dialog-buttonpane span").click();
    cy.location("href").should("eq", "undefined");
    cy.get("button.ui-state-hover > span").click();
    cy.location("href").should("eq", "http://msap-integrado.qa.simonettidev.com.br/webpdv/vendas/atendimento.php?f_int_storeno=25&f_int_ordno=611973");
    cy.get("#uso th").click();
    cy.get("a").click();
    cy.get("[data-cy='constructorFlowProceedButton']").click();
    cy.get("form > div.d-flex span").click();
    cy.get("#input-87").click();
    cy.get("div > div > div > div.fill-height h2").click();
    cy.get("[data-cy='screenSignature']").click();
    cy.get("[data-cy='saveSignature']").click();
    cy.get("img").click();
    cy.get("[data-cy='sendSignatureButton']").click();
    cy.get("form > div.d-flex span").click();
  });
});
